CREATE TABLE IF NOT EXISTS audit.etl_run (
    etl_run_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    process_name text NOT NULL,
    started_at timestamptz NOT NULL DEFAULT current_timestamp,
    completed_at timestamptz,
    status text NOT NULL,
    rows_extracted integer NOT NULL DEFAULT 0,
    rows_loaded integer NOT NULL DEFAULT 0,
    rows_rejected integer NOT NULL DEFAULT 0,
    warning_count integer NOT NULL DEFAULT 0,
    error_count integer NOT NULL DEFAULT 0,
    message text,
    CONSTRAINT etl_run_status_chk CHECK (status IN ('STARTED', 'SUCCEEDED', 'FAILED', 'PARTIAL'))
);

CREATE TABLE IF NOT EXISTS audit.source_file (
    source_file_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    etl_run_id bigint,
    file_name text NOT NULL,
    file_path text,
    file_hash text,
    row_count integer,
    extracted_at timestamptz,
    registered_at timestamptz NOT NULL DEFAULT current_timestamp,
    CONSTRAINT source_file_etl_run_fk FOREIGN KEY (etl_run_id) REFERENCES audit.etl_run(etl_run_id)
);

CREATE TABLE IF NOT EXISTS audit.data_quality_issue (
    issue_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    etl_run_id bigint,
    source_event_id bigint,
    rule_code text NOT NULL,
    severity text NOT NULL,
    field_name text,
    invalid_value text,
    description text NOT NULL,
    detected_at timestamptz NOT NULL DEFAULT current_timestamp,
    resolved boolean NOT NULL DEFAULT false,
    resolved_at timestamptz,
    resolution_note text,
    CONSTRAINT dq_issue_etl_run_fk FOREIGN KEY (etl_run_id) REFERENCES audit.etl_run(etl_run_id),
    CONSTRAINT dq_issue_severity_chk CHECK (severity IN ('INFO', 'WARNING', 'ERROR'))
);

CREATE INDEX IF NOT EXISTS idx_source_file_etl_run_id ON audit.source_file(etl_run_id);
CREATE INDEX IF NOT EXISTS idx_data_quality_issue_etl_run_id ON audit.data_quality_issue(etl_run_id);
CREATE INDEX IF NOT EXISTS idx_data_quality_issue_source_event_id ON audit.data_quality_issue(source_event_id);
CREATE INDEX IF NOT EXISTS idx_data_quality_issue_rule_code ON audit.data_quality_issue(rule_code);
CREATE INDEX IF NOT EXISTS idx_data_quality_issue_severity ON audit.data_quality_issue(severity);
